### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by sshchmod777** [jiowcl/MQL-CopyTrade#3]
Hello, the source doesn't compile anymore using the updated version of MT4. How to fix it?

**Comment by jmarunix** [comment]
> Hello, the source doesn't compile anymore using the updated version of MT4. How to fix it?

Hi @sshchmod777, what is your mt4 version?
I have just downloaded the Metatrader 4 IC Markets 4.00 build 1260 24 Jan 2020, and works very fine. Maybe i am outdated ;-)

**Comment by sshchmod777** [comment]
Hey there! I was able to compile it. I just have to download its dependencies to complete the compilation. It works flawlessly. Also, I'm trying to add some features such as an option to use stop loss or not, filter orders based on comment and don't copy existing trades. 

Clarification on some settings:

MinLots - It will only copy trades from source if the lot size is above minimum?
MaxLots - It will only copy trades from source if the lot size is less than the max lots?

Thank you!

**Comment by jmarunix** [comment]
Hi again @sshchmod777, 
I only have tested the MaxLots config: 
If the Publisher puts an order, for example, of 11 lots size, and you config the Suscriber with MaxLots=10, the order copied will only have 10 lots then. 
We can suppose MinLots will be the minimum lots for the copied orders in the order way, you can test it with demo accounts.

And if you could solve this issue, please close it :-)

**Comment by sshchmod777** [comment]
Got it! I just added an option to open only trades according to min/max lot size used by the publisher.

All good for the issue. Thank you!
