### ISSUE TITLE
I am doing something wrong

### ISSUE THREAD

**Issue by victalejo** [jiowcl/MQL-CopyTrade#4]
I don't know what I'm doing wrong but I get the following error

> 2020.06.25 22:40:32.727	Script JiowclPublisherServer USDJPY,H4: removed
2020.06.25 22:40:32.726	JiowclPublisherServer USDJPY,H4: global initialization failed
2020.06.25 22:40:32.725	JiowclPublisherServer USDJPY,H4: unresolved import function call
2020.06.25 22:40:32.725	Cannot call 'libzmq.dll::zmq_ctx_new', 'libzmq.dll' is not loaded
2020.06.25 22:40:32.724	Cannot load 'C:\Users\VICTALEJO\AppData\Roaming\MetaQuotes\Terminal\CBAD7D1B35A2FBD485DA10342CF7119A\MQL4\Scripts\libzmq.dll' [126]
2020.06.25 22:40:32.604	JiowclPublisherServer USDJPY,H4 inputs: Server=tcp://*:5559; ServerDelayMilliseconds=300; ServerReal=false; AllowSymbols=; 
2020.06.25 22:40:31.399	Script JiowclPublisherServer USDJPY,H4: loaded successfully
2020.06.25 22:26:37.525	Script JiowclSubscriberClient USDJPY,H4: removed
2020.06.25 22:26:37.523	JiowclSubscriberClient USDJPY,H4: global initialization failed
2020.06.25 22:26:37.522	JiowclSubscriberClient USDJPY,H4: unresolved import function call
2020.06.25 22:26:37.522	Cannot call 'libzmq.dll::zmq_ctx_new', 'libzmq.dll' is not loaded
2020.06.25 22:26:37.522	Cannot load 'C:\Users\VICTALEJO\AppData\Roaming\MetaQuotes\Terminal\CBAD7D1B35A2FBD485DA10342CF7119A\MQL4\Scripts\libzmq.dll' [126]
2020.06.25 22:26:37.499	JiowclSubscriberClient USDJPY,H4 inputs: Server=tcp://localhost:5559; ServerDelayMilliseconds=300; ServerReal=false; SignalAccount=; MinLots=0.0; MaxLots=0.0; PercentLots=100.0; Slippage=3; AllowOpenTrade=true; AllowCloseTrade=true; AllowModifyTrade=true; AllowSymbols=; InvertOrder=false; MinFreeMargin=0.0; SymbolPrefixAdjust=; 
2020.06.25 22:26:34.589	Script JiowclSubscriberClient USDJPY,H4: loaded successfully

**Comment by jiowcl** [comment]
Hi,

Please extract the attach file into MQL4 folder, and make sure the option `Allow DLL imports` is checked.

[Libraries.zip](https://github.com/jiowcl/MQL-CopyTrade/files/4841979/Libraries.zip)
