### ISSUE TITLE
Publisher Hosted in VPS

### ISSUE THREAD

**Issue by jayaruvan** [jiowcl/MQL-CopyTrade#5]
My publisher hosted in VPS and it has static IP.
In this scenario, this solution not work.

However in the local environment, both copy mt4 and server mt4 same PC, this works. I have changed listen IP to static.

**Comment by jayaruvan** [comment]
bump

**Comment by jiowcl** [comment]
Hi,

Have you set up a firewall?

**Comment by jayaruvan** [comment]
yes, it is allowed in the firewall. 
How can I proceed?

**Comment by jayaruvan** [comment]
bump

**Comment by jayaruvan** [comment]
bump

**Comment by jayaruvan** [comment]
bump

**Comment by jiowcl** [comment]
I use different PC as Publisher and Subscriber and they work perfect, 
maybe you should check the VPS settings.

**Comment by jayaruvan** [comment]
Thank you. I'l ltry with different VPS. 

Can I know your MQTT Broker  I have checked with Mosquitto / Centos 7 env.

Thank you.

**Comment by jiowcl** [comment]
MQTT Broker?
