### ISSUE TITLE
how to customize copy trader

### ISSUE THREAD

**Issue by pujamohanty** [jiowcl/MQL-CopyTrade#7]
Hi
we want to 
1. disable market order, 
2. enforce stop loss in the pending order 
3.  use a fixed risk% and 
4.  auto calculate the lot size based upon a certain capital size instead of equity. 
Could you please help us with this?

**Comment by jiowcl** [comment]
Hi,

Look like a good idea.

Maybe it’s a customized project.

**Comment by pujamohanty** [comment]
> Hi,
> 
> Look like a good idea.
> 
> Maybe it’s a customized project.

Yes it is a custom project. My Colleague Daniel has sent you email.
